-- Onflow Reports Schema
-- This schema defines the table structure for storing UX testing reports

CREATE TABLE IF NOT EXISTS public.onflow_reports (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  generated_at timestamp with time zone NOT NULL,
  url text NOT NULL,
  num_personas integer NOT NULL,
  num_tests integer NOT NULL,
  successful_tests integer NOT NULL,
  failure_rate text NOT NULL,
  personas jsonb NOT NULL,
  report_data jsonb NOT NULL,
  CONSTRAINT onflow_reports_pkey PRIMARY KEY (id)
) TABLESPACE pg_default;

-- Indexes for performance optimization
CREATE INDEX IF NOT EXISTS idx_onflow_reports_created_at
  ON public.onflow_reports USING btree (created_at DESC)
  TABLESPACE pg_default;

CREATE INDEX IF NOT EXISTS idx_onflow_reports_generated_at
  ON public.onflow_reports USING btree (generated_at DESC)
  TABLESPACE pg_default;

CREATE INDEX IF NOT EXISTS idx_onflow_reports_url
  ON public.onflow_reports USING btree (url)
  TABLESPACE pg_default;

CREATE INDEX IF NOT EXISTS idx_onflow_reports_url_generated
  ON public.onflow_reports USING btree (url, generated_at DESC)
  TABLESPACE pg_default;

-- Enable Row Level Security
ALTER TABLE public.onflow_reports ENABLE ROW LEVEL SECURITY;

-- Create policy to allow public read access to reports
CREATE POLICY "Allow public read access"
  ON public.onflow_reports
  FOR SELECT
  USING (true);

-- Create policy to allow authenticated users to insert reports
CREATE POLICY "Allow authenticated users to insert reports"
  ON public.onflow_reports
  FOR INSERT
  WITH CHECK (true);

-- Comments for documentation
COMMENT ON TABLE public.onflow_reports IS 'Stores UX testing reports generated by the Onflow platform';
COMMENT ON COLUMN public.onflow_reports.id IS 'Unique identifier for the report';
COMMENT ON COLUMN public.onflow_reports.created_at IS 'Timestamp when the record was created in the database';
COMMENT ON COLUMN public.onflow_reports.generated_at IS 'Timestamp when the report was generated';
COMMENT ON COLUMN public.onflow_reports.url IS 'Target URL that was tested';
COMMENT ON COLUMN public.onflow_reports.num_personas IS 'Number of test personas used';
COMMENT ON COLUMN public.onflow_reports.num_tests IS 'Total number of tests executed';
COMMENT ON COLUMN public.onflow_reports.successful_tests IS 'Number of successful tests';
COMMENT ON COLUMN public.onflow_reports.failure_rate IS 'Percentage of failed tests as a string (e.g., "25%")';
COMMENT ON COLUMN public.onflow_reports.personas IS 'JSONB array containing persona details and test results';
COMMENT ON COLUMN public.onflow_reports.report_data IS 'JSONB object containing full report metadata and results';
